### PR TITLE
dnssec: verify DS digests and signatures without the library's fixed buffers

### PR DESCRIPTION
**Pull request by semihalev**
## Problem

Two DNSSEC leaves dominate the field profile, and both spend most of their bytes on a buffer sized for a message rather than for the work: `DNSKEY.ToDS` at **3.83%** of everything the process allocates, and `RRSIG.Verify` at **7.94%**.

Checking a delegation asks one question — does this key hash to the parent's DS digest — and answered it by building the DS record the key would produce, then comparing the two hexadecimal renderings. Per candidate key, per DS, per delegation, that is a 4096-octet key buffer, a 255-octet owner buffer, the `dns.DS` itself, its key tag and a hex string. The digest is the only part anyone wanted.

Verifying a signature is the same shape. The library packs the canonical signed data into a fixed 4096-octet buffer for every signature of every response, whatever the RRset's actual size, and re-derives the key material and key tag on each one.

## Change

**DS digest.** The digest is computed straight into the comparison: canonical owner name, flags, protocol, algorithm and the decoded public key, hashed and matched against the parent's digest bytes. The parent's digest is decoded once for the whole candidate set instead of being re-rendered per candidate. The work accounting is unchanged — `runDSDigestMatch` charges the request tree exactly as `runDSDigest` did, so an attacker-driven key set still meets the same ceiling.

**Signature verification.** The canonical signed data is this package's own — the construction the wide-exponent RSA path has always used — and the cryptography stays in the standard library. RSA, ECDSA P-256/P-384 and Ed25519 are implemented; any other algorithm is refused rather than guessed at, and stays on the library's path.

Both keep the library's acceptance envelope deliberately. `ToDS` packs into a fixed buffer, so a key larger than 4092 octets produces no DS and could never match; computing the digest directly has no ceiling of its own, and gaining one silently would let a key the library refuses become a chain of trust. The limit is applied to the *encoded* length, before the decode — an attacker-supplied DNSKEY can be as large as the message allows, and deciding it is too big after materializing it pays for the very thing being refused.

## Divergences, on purpose

Three, each of them narrowing what is accepted, each with a test that fails if the divergence closes or widens:

- **ECDSA signature length.** RFC 6605 §4 fixes r and s at the curve's width. The library splits whatever it is handed in half and lets leading zeros pass; a zero-padded 66-octet P-256 signature is not a P-256 signature, and is refused here.
- **DS digest type 5.** miekg names its constant `SHA512`, following an expired draft. IANA assigns 5 to GOST R 34.11-2012 (RFC 9558), and this resolver's `IsSupportedDSDigest` admits only 1, 2 and 4. Treating a GOST digest as a SHA-512 one is the error worth refusing, so type 5 is not computed.
- **Signer containment.** The library tests it with a plain string suffix — its own comment concedes that is the best it can do without SOA context — which reads `evilexample.com.` as inside `example.com.` It is now a label boundary, through the shared helper described below.

A fourth is the RSA modulus bounds, in both directions and both narrowing: below 1024 bits each path refuses by default, but the library's floor is crypto/rsa's and lifts under `GODEBUG=rsa1024min=0` while this package's own does not; above 4096 bits the library has no bound and this package refuses.

## Zone containment is decided on labels

Review found a defect in the shared containment helper, and it predates this branch. `NameInZone` tested containment with a string suffix, and an escaped dot is not a label separator: `foo\.example.com.` is the two labels `foo.example` and `com`, outside `example.com.` entirely, while ending with its text. A validly signed RRset with that owner authenticated against the zone's own key on the production `VerifyRRSIG` path — a zone operator could sign answers for owners no delegation ever gave them.

The fix is in the one helper every containment check in the resolver comes through, and is escape-aware: a dot is a separator exactly when an even number of backslashes precede it. It also compares in place instead of building `"."+zone` per call — free on the stack for a short zone, a heap allocation once the zone name reaches the runtime's 32-octet temporary buffer, which ordinary delegation names do.

Both levels are pinned: a table over the helper, and a signed `VerifyRRSIG` regression that authenticates nothing while the genuine `foo.zone.example.` still validates.

## The size check runs before the decode, on the path a query takes

The first version of the DS limit was applied inside `dsDigestMatches`, and the test that proved it measured `dsDigestMatches`. `VerifyDS` reaches `usableDSCandidate` first, and that begins with `KeyTag` — which packs the key into a buffer of its own and decodes the material to fill it. Nothing about that decode depends on which DS is being considered, so a DS RRset naming the same key repeatedly paid for it once per mention:

| 48 KiB key, 32 DS records | allocated per `VerifyDS` |
|---|---|
| limit after `KeyTag` | 1,580,192 B |
| limit before `KeyTag` | **5,792 B** (−99.6%) |

The remainder is the deduplication and sort of 32 DS records, which allocate by design. The regression measures `VerifyDS` itself, in bytes, with a ceiling of one key's worth of material: crossing it means at least one decode happened.

One narrowing came with it and is fixed rather than documented. The decoder skips CR and LF, so a key at exactly the maximum, wrapped into lines, measures longer than the limit while decoding to a packable key. The check counts line breaks out — on the oversized branch only, and bounded by the limit rather than by what was sent: once limit+1 octets of material have been seen, nothing in the rest can bring the decoded length back under it. The unwrapped case, which is every real one, is settled by two byte searches instead of a walk. Refusing the 32-record set above costs **12 µs**, against 62 µs for the full walk.

`resolver.go`'s key-map build is deliberately left alone. It calls `KeyTag` once per DNSKEY and is bounded by the message that carried them, so there is no amplification to remove; and the same map feeds `VerifyRRSIGWithWork`, where a ceiling that exists because `ToDS` packs into a fixed buffer has no business deciding which keys may verify a signature. Removing that cost properly means computing the key tag without the library's buffer, which is a change of its own.

## Canonical ordering

Writing the differential tests surfaced a defect in this package's own signed-data construction, not the library's. RFC 4034 §6.3 orders an RRset by canonical **RDATA**; the code claimed to reproduce `rawSignatureData` and instead sorted whole wire records, owner name included. Every RR in an RRset shares an owner, so the prefix is identical and the comparison usually reaches the RDATA anyway — but not when RDLENGTH differs, which is where the ordering matters.

The fix computes the RDATA offset once by walking the label lengths of the shared owner, and sorts from there. No unpack, no per-record string, no parallel slice: the benchmark is unchanged. A `TXT "a" "zzzz"` / `TXT "b"` fixture pins it — a single-string TXT cannot tell the two orderings apart, because its RDATA begins with a length octet that correlates with RDLENGTH.

## Measurements

DS digest, same key and digest type, matching the library's own digest:

| | `ToDS` + compare | digest compare |
|---|---|---|
| bytes/op | 4,992 B | **356 B** (−93%) |
| allocs/op | 9 | **5** |
| ns/op | ~630 | **~235** |

Signature verification, per signature, bytes/op — the fixed buffer, gone:

| algorithm | library | owned |
|---|---|---|
| RSASHA256 | 6,584 B | **2,832 B** (−57%) |
| RSASHA512 | 6,712 B | **2,960 B** (−56%) |
| ECDSAP256SHA256 | 6,632 B | **2,800 B** (−58%) |
| ECDSAP384SHA384 | 7,168 B | **3,336 B** (−53%) |
| ED25519 | 5,016 B | **1,168 B** (−77%) |

`ns/op` is within noise on every algorithm — the crypto dominates, and that is the point: the bytes go without paying for them.

## Tests

The digest and the signature must be the library's verdict, not merely a plausible one, so the tests are differential.

Digest, across nine keys — RSA/SHA-256, RSA/SHA-512, ECDSA P-256 and P-384, Ed25519, the root zone, a shouted owner name, an IDN label, a revoked key and a zone-signing key (the flags are hashed, so those are distinct inputs) — and every digest type the library computes: it accepts exactly what `ToDS` produces; refuses a digest altered in one bit, a truncated one, and any other key's; refuses the digest types the library refuses; folds the owner name before hashing; and refuses an oversized key in **0 allocations**, which is what pins the limit ahead of the decode rather than behind it.

Signature, for each of the six algorithms: the signature as signed, one altered octet, an RRset altered after signing, a truncated RRset, another key of the same algorithm, and each binding the preflight owns — key tag, signer, covered type, label count, zone flag, protocol. Every one of them must reach the same verdict as `dns.RRSIG.Verify`.

Wide-exponent RSA keeps its own coverage, including a recorded ccTLD vector, and now checks that the path rejects as well as accepts.

`go test ./... -race`, `go vet` and `golangci-lint` are clean.

### CODE REVIEW

**Comment by semihalev** [comment]
## The second leaf, on the same branch

`RRSIG.Verify` is the largest single allocation site in the process at **7.94%**, nearly all of it a fixed 4096-octet buffer holding the signed data whatever the data actually is, plus re-deriving the key material and key tag on every signature.

This package already builds the canonical signed data itself — it has to, for RSA keys whose exponent `crypto/rsa` refuses to load — and that construction is documented as a faithful reproduction of the library's. Verification now goes through it for RSA, ECDSA and Ed25519. The cryptography stays in the standard library: `crypto/rsa`, `crypto/ecdsa` and `crypto/ed25519` do the mathematics, and the raw modular exponentiation remains for the wide exponents it was written for. An algorithm this does not implement is left on the library's path rather than guessed at.

| per signature | library | owned |
|---|---|---|
| RSASHA256 | 6,584 B / 38 | **2,832 B** / 40 |
| RSASHA512 | 6,712 B / 38 | **2,960 B** / 40 |
| ECDSAP256SHA256 | 6,632 B / 52 | **2,800 B** / 51 |
| ECDSAP384SHA384 | 7,168 B / 59 | **3,336 B** / 58 |
| ED25519 | 5,016 B / 25 | **1,168 B** / 24 |

Time is unchanged across all of them — the cryptography dominates and has not moved.

**The tests are differential, and that is the whole of the argument.** For a signed RRset per algorithm, and for a signature altered in one octet, a record altered after signing, a truncated RRset, another key, a mismatched key tag, a foreign signer, a wrong covered type, an impossible label count, a non-zone key and a wrong protocol, this must reach *the same verdict as* `dns.RRSIG.Verify` — not a verdict of its own that looks right.

One thing this removes: the wide-exponent entry point is gone, because the dispatcher no longer reaches it. Its tests now exercise the path that actually runs, which they should have been doing the moment that path changed.

`go test ./middleware/... -race`, `go vet` and `golangci-lint` are clean. The full suite passes apart from `server.TestCertManagerConcurrency`, which flakes under whole-suite load for a pre-existing reason unrelated to this branch (`server_test.go` writes certificates to a fixed `os.TempDir()` path shared between tests) and passes on its own.

**Comment by semihalev** [comment]
## Both blockers closed

### P1 — canonical ordering (reproduced, fixed)

You're right, and it is worse than a style point: **the library signs and accepts an RRset this branch rejected**. RFC 4034 §6.3 sorts an RRset by its RDATA and by nothing before it; the sort compared whole packed records, and RDLENGTH sits between the owner and the data, so records whose lengths and contents order differently were hashed in an order no signer used.

Reproducing it took a second attempt worth recording: a single-string TXT does *not* separate the two rules, because TXT's RDATA begins with a length octet that moves with RDLENGTH. `TXT "a" "zzzz"` against `TXT "b"` does — the longer RDATA starts with the smaller octets — and against the parent commit it fails with `dns: bad signature` on a signature `sig.Verify` accepts.

This is older than the branch: it is in the construction documented as a faithful reproduction of the library's, which it was not. What the branch did was widen it from wide-exponent RSA to every signature. Without your catch it would have bogused multi-string TXT sets in production.

**On the allocation cost you flagged**: the first fix was wasteful and you were right to stop it. `UnpackDomainName` builds a name string per record purely to measure it, and I had added a parallel slice on top. The offset is now found **once for the whole set** — the records share an owner and canonicalization has already given them the same spelling — by walking the label lengths, which allocates nothing. Verification measures exactly what it did before the fix: 2,832 B / 40 allocs for RSASHA256, unchanged.

There is now a differential test on the canonical form itself, comparing it byte for byte with the library's ordering over sets where length order and content order disagree.

### P1 — DS acceptance envelope (fixed)

Also right. The library packs a key into a fixed buffer to build a DS, so material larger than it holds produces no DS and can never match; computing the digest directly accepted it. A chain of trust must not become valid because the check got cheaper. Decoded key material is capped at 4092 octets, and the test pins both sides of the boundary — the largest key the library packs is accepted, one octet past it is refused even when handed the digest such a key would have.

### P2 — digest type 5 (fixed)

Correct, and I had it backwards in the previous round: I "fixed" a test by treating 5 as supported because miekg's constant is named `SHA512`. IANA assigns 5 to GOST R 34.11-2012 (RFC 9558), the resolver's own `IsSupportedDSDigest` admits only 1, 2 and 4, and computing a GOST digest as SHA-512 is exactly the error to refuse.

The case is gone. The test now states the divergence explicitly rather than asserting agreement: it checks that the library still computes 5, that this resolver still does not admit it, and that we refuse the library's value for it — so if `IsSupportedDSDigest` ever changes, the test says the two have to be revisited together.

### P2 — EDE codes (fixed)

A signature that does not decode, or does not have the shape its algorithm requires, reports a bad signature rather than a missing key. The verdict was already right; what the client was told was not.

`go test ./middleware/... -race`, `go vet` and `golangci-lint` are clean. The full suite passes apart from the pre-existing `server.TestCertManagerConcurrency` flake, which passes on its own.

**Review by m3ok — APPROVED** [review]
